DROP TABLE IF EXISTS "android_metadata";
CREATE TABLE android_metadata (locale TEXT);
INSERT INTO "android_metadata" VALUES('pt_BR');
DROP TABLE IF EXISTS "hints";
CREATE TABLE "hints" ("_id" INTEGER PRIMARY KEY, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "password" TEXT NOT NULL);
INSERT INTO "hints" VALUES(1, 'Instruções iniciais', 'Isabela, você já é uma especialista quando se trata de caça ao tesouro, por isso você não terá vida fácil por aqui! Hahaha. Mas não se preocupe, eu sei que você consegue. :) Lhe serão propostos vários desafios, que podem estar em locais não tão próximos, portanto, podem levar algumas boas horas desvendando os segredos... Cada pista contém uma enigma que dará acesso a uma palavra-chave que abre a próxima dica. Quando você descobrir a resposta, clique no botão acima e digite a resposta. Está pronta? A próxima pista está em um local em que você se encontra com a beleza em pessoa TODOS os dias.', 'park shopping');
INSERT INTO "hints" VALUES(2, 'Um local pouco explorado', 'A próxima pista está em um lugar que, segundo os seus pais, você não costuma ir muito. Hora de dar uma vasculhada e conhecer sua própria casa hehe.', 'bicicleta');
INSERT INTO "hints" VALUES(3, 'No escurinho do cinema', 'Comédia, romance, suspense ou ação? Independente do gênero, qualquer filme se torna perfeito se eu estiver com a melhor companhia: você. Então corra e escolha um filme que a sessão vai começar!', 'aço');
INSERT INTO "hints" VALUES(4, 'Gordice', 'Assistir um filme assim em casa, um doce cairia bem... Pegue os ingredientes e faça aquele brigadeiro gostoso antes que o filme comece! :9', 'meio amargo');
INSERT INTO "hints" VALUES(5, 'Próximo nível', 'Parabéns, você está indo muito bem! Você já está pegando o jeito. Mas sei que você deve estar achando tudo isso muito fácil. Então está na hora de começar nossa aventura pela cidade! Não sei por quanto tempo isso durará, então se prepare e leve o que você achar necessário para sua sobrevivência. Não tenha receio do que virá, sê valente e corajosa! A próxima dica está à sua espera em um lugar onde as crianças gostam de brincar.', '2');
INSERT INTO "hints" VALUES(6, 'Aventuras no parque', 'Exatamente! Fomos ao parque duas vezes juntos! Na primeira vez fomos com os casais de namorados dos adolas participar de um piquenique, e na segunda fomos com sua família fazer uma caminhada. Então vamos começar dando um passeio pelo parque? Partiu!', '14');
INSERT INTO "hints" VALUES(7, 'Quá quá', 'Sim, existem várias pistas escondidas no parque e seu objetivo é encontrar todas elas. Use seu GPS para se guiar e procure por mapas em pontos específicos do parque para te ajudar. Investigue, pergunte e procure. Você pode passar por alguns desafios no caminho, por tanto seja corajosa! Pista: em um banco preciso me sentar para observar os patinhos a nadar.', 'caldas novas');
INSERT INTO "hints" VALUES(8, 'Hora de relaxar', 'Que tal assistir a uma partida de vôlei de praia?', 'asdf');
INSERT INTO "hints" VALUES(9, 'Coco', 'Água de coco com dica', 'asdf');
INSERT INTO "hints" VALUES(10, 'Bambuzal', 'Foto.', 'asdf');
INSERT INTO "hints" VALUES(11, 'Metrô', 'Metrô.', 'asdf');
INSERT INTO "hints" VALUES(12, 'Igreja', 'Igreja.', 'asdf');
INSERT INTO "hints" VALUES(13, 'Carona', 'Pegue uma carona.', 'asdf');
INSERT INTO "hints" VALUES(14, 'Pontão', 'Coloque a venda', 'asdf');
